employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.listview, name='list' ),
    path('add/', views.createview, name='create'),
    path('<id>/edit', views.editview, name='edit'),
    path('<id>/delete', views.deleteview, name='delete'),
    path('<id>/detail', views.detailview, name='detail'),
]

mails/urls.py
from django.urls import path
from . import views

app_name = 'mails'

urlpatterns = [
    path('', views.email, name = 'list' ),
]

ticket_ms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('organizations/', include('organizations.urls')),
    path('tickets/', include('tickets.urls')),
    path('employees/', include('employees.urls')),
    path('products/', include('products.urls')),
    path('mails/', include('mails.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'

urlpatterns = [
    path('', views.listview, name='list'),
    path('add/', views.createview, name='create'),
    path('<id>/edit/', views.editview, name='edit'),
    path('<id>/delete/', views.deleteview, name='delete'),
    path('branch_list/', views.branch_listview, name='branch_list'),
    path('branch_add/', views.branch_create_view, name='branch_create'),
    path('branch_list/<id>/branch_edit/', views.branch_edit_view, name='branch_edit'),
    path('branch_list/<id>/branch_delete/', views.branch_delete_view, name='branch_delete'),
    path('problem_list/', views.problem_listview, name='problem_list'),
    path('problem_add/', views.problem_create_view, name='problem_create'),
    path('problem_list/<id>/branch_edit/', views.problem_edit_view, name='problem_edit'),
    path('problem_list/<id>/branch_delete/', views.problem_delete_view, name='problem_delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change_password/', views.user_password_change, name='change_password'),
    path('users/', views.user_listview, name='list'),
    path('users/<id>/edit/', views.user_editview, name='edit'),
    path('users/<id>/delete/', views.user_deleteview, name='delete'),
    path('users/add/', views.user_createview, name='create'),
]

tickets/models.py
from django.db import models
from model_utils import Choices
from employees.models import Employee

# Create your models here.
SOURCE = Choices(
        'Call_in',
        'Call_out',
        'CUG',
        'Viber',
        'Skype',
        'Message',
    )
STATUS = Choices(
    'Open',
    'Close',
    'Pending',
)


class Branch(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ProblemDomain(models.Model):
    problem = models.CharField(max_length=255)

    def __str__(self):
        return self.problem


class Ticket(models.Model):
    issue_date = models.DateField(auto_now_add=True, auto_now=False)
    client_id = models.CharField(max_length=255)
    contact = models.CharField(max_length=255, null=True, blank=True)
    branch_id = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)
    problem_domain_id = models.ForeignKey(ProblemDomain, on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default=STATUS.Open)
    remarks = models.CharField(max_length=255, null=True)
    ticket = models.CharField(max_length=255, null=True, blank=True)
    source = models.CharField(max_length=10, choices=SOURCE, default=SOURCE.Call_in)
    employee_id = models.ForeignKey(Employee, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.client_id

    @property
    def attached_file_url(self):
        if self.attached_file and hasattr(self.attached_file, 'url'):
            return self.attached_file.url

tickets/forms.py
from django import forms

from .models import Ticket, Branch, ProblemDomain


class CreateForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'client_id',
            'contact',
            'branch_id',
            'problem_domain_id',
            'status',
            'remarks',
            'ticket',
            'source',
            'employee_id',
        ]
        widgets = {
            'client_id': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'client_id'}),
            'contact': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'contact number'}),
            'branch_id': forms.Select(attrs={'class': 'form-control'}),
            'problem_domain_id': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'remarks': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'description'}),
            'ticket': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ticket number'}),
            'source': forms.Select(attrs={'class': 'form-control'}),
            'employee_id': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(CreateForm, self). __init__(*args, **kwargs)
        self.fields['employee_id'].required = True


class CreateBranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = [
            'name',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'branch name'}),
        }


class CreateProblemForm(forms.ModelForm):
    class Meta:
        model = ProblemDomain
        fields = [
            'problem',
        ]
        widgets = {
            'problem': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'problem'}),
        }

tickets/views/branch_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from tickets.forms import CreateBranchForm
from tickets.models import Branch
from users.decorators import admin_required


@login_required
def branch_listview(request):
    queryset = Branch.objects.all()
    context = {
        'branch_list': queryset
    }
    template_name = 'tickets/branch_list.html'
    return render(request, template_name, context)


@admin_required
@login_required
def branch_create_view(request):
    form = CreateBranchForm(request.POST or None)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Branch added.")
        return redirect('tickets:branch_list')
    if form.errors:
        errors = form.errors

    template_name = 'tickets/branch_forms.html'
    context = {
        'form': form,
        'errors': errors
    }
    return render(request, template_name, context)


@admin_required
@login_required
def branch_edit_view(request, id=None):
    instance = get_object_or_404(Branch, id=id)
    form = CreateBranchForm(request.POST or None, instance=instance)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Branch edited.")
        return redirect(reverse('tickets:branch_list'))
    if form.errors:
        errors = form.errors

    template_name = 'tickets/branch_edit.html'
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)


@admin_required
@login_required
def branch_delete_view(request, id=None):
    instance = get_object_or_404(Branch, id=id)
    instance.delete()
    messages.info(request, "Branch deleted.")
    return redirect('tickets:branch_list')

tickets/views/problem_domain_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from tickets.forms import CreateProblemForm
from tickets.models import ProblemDomain
from users.decorators import admin_required


@login_required
def problem_listview(request):
    queryset = ProblemDomain.objects.all()
    context = {
        'problem_list': queryset
    }
    template_name = 'tickets/problem_list.html'
    return render(request, template_name, context)


@admin_required
@login_required
def problem_create_view(request):
    form = CreateProblemForm(request.POST or None)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Problem domain added.")
        return redirect('tickets:problem_list')
    if form.errors:
        errors = form.errors

    template_name = 'tickets/problem_forms.html'
    context = {
        'form': form,
        'errors': errors
    }
    return render(request, template_name, context)


@admin_required
@login_required
def problem_edit_view(request, id=None):
    instance = get_object_or_404(ProblemDomain, id=id)
    form = CreateProblemForm(request.POST or None, instance=instance)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Problem domain edited.")
        return redirect(reverse('tickets:problem_list'))
    if form.errors:
        errors = form.errors

    template_name = 'tickets/problem_edit.html'
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)


@admin_required
@login_required
def problem_delete_view(request, id=None):
    instance = get_object_or_404(ProblemDomain, id=id)
    instance.delete()
    messages.info(request, "Problem domain deleted.")
    return redirect('tickets:problem_list')

tickets/views/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from ticket_ms import settings
from tickets.filters import TicketFilter
from users.decorators import admin_required
from tickets.models import Ticket, Branch
from tickets.forms import CreateForm


# Create your views here.

@login_required
def listview(request):
    # source_filter = request.GET.get('source')
    # status_filter = request.GET.get('status')
    # if source_filter or status_filter:
    #     query = Ticket.objects.filter(source=source_filter) or Ticket.objects.filter(status=status_filter)
    #     context = {
    #         'object_list': query,
    #         'source_filter': source_filter,
    #         'status_filter': status_filter,
    #     }
    #
    # else:
    #     query = Ticket.objects.all()
    #     context = {
    #         'object_list': query,
    #     }

    query = Ticket.objects.all()
    ticket_filter = TicketFilter(request.GET, queryset=query)
    context = {
        'filter': ticket_filter
    }
    template = 'tickets/list.html'
    return render(request, template, context)



@login_required
def createview(request):
    form = CreateForm(request.POST, request.FILES)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        email_id = instance.employee_id.email
        instance.save()
        messages.success(request, "Record added.")

        subject = 'Mail Testing'
        message = 'Zeftware Solutions Generate Tickets for you. Please login and see the ticket.'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [email_id]

        send_mail(subject, message, email_from, recipient_list, fail_silently=False)

        return HttpResponseRedirect("/tickets/")
    if form.errors:
        errors = form.errors

    template_name = 'tickets/forms.html'
    context = {
        "form": form,
        "errors": errors
    }
    return render(request, template_name, context)


@login_required
def editview(request, id=None):
    instance = get_object_or_404(Ticket, id=id)
    form = CreateForm(request.POST or None, request.FILES or None, instance=instance)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Record edited.")
        return HttpResponseRedirect("/tickets/")
    if form.errors:
        errors = form.errors

    template_name = 'tickets/form.html'
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)


@admin_required
@login_required
def deleteview(request, id=None):
    instance = get_object_or_404(Ticket, id=id)
    instance.delete()
    messages.info(request, "Record deleted.")
    return redirect('tickets:list')

tickets/templates/tickets/branch_edit.html
{% extends "base.html" %}
{% block head_title %} {{ title }} | {{ block.super }} {% endblock head_title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'tickets:branch_list' %}">Branches</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Branch</li>
    </ol>
</nav>
<hr>

<form method="POST" enctype="multipart/form-data" class="offset-md-4"> {% csrf_token %}
    <div class="form-group row">
        <label class="col-md-1 col-form-label">{{ form.name.label }}</label>
        <div class="col-md-6">
            {{ form.name }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary offset-md-1">Edit branch</button>
</form>

{% endblock %}

tickets/templates/tickets/branch_forms.html
{% extends "base.html" %}
{% block head_title %} {{ title }} | {{ block.super }} {% endblock head_title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'tickets:branch_list' %}">Branches</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Branch</li>
    </ol>
</nav>
<hr>

<form method="POST" enctype="multipart/form-data" class="offset-md-4"> {% csrf_token %}
    <div class="form-group row">
        <label class="col-md-1 col-form-label">{{ form.name.label }}</label>
        <div class="col-md-6">
            {{ form.name }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary offset-md-1">Add branch</button>
</form>

{% endblock %}

tickets/templates/tickets/branch_list.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} Tickets|{{ block.super }} {% endblock head_title %}
{% block content %}
    {%  if user.is_admin %}
    <div style="float:right">
        <a href='{% url "tickets:branch_create" %}' class="btn btn-primary" style="margin-top:8px;">Add Branch</a>
    </div>
    {% endif %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page"> Branches </li>
        </ol>
    </nav>
    <hr>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable ">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ message.tags }} !!</strong> {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <table class="table table-bordered table-hover col-md-4 offset-4">
        <thead>
        <tr>
            <th>S.N.</th>
            <th>Name</th>
            {%  if user.is_admin %}
            <th>Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for branch in branch_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td> {{ branch }}</td>
                {%  if user.is_admin %}
                <td>
                    <a href="{% url 'tickets:branch_edit' branch.id %}">
                        <i class="fas fa-pen-square" title="edit"></i>
                    </a> &nbsp;
                    <a href="{% url 'tickets:branch_delete' branch.id %}" data-toggle="modal"
                       data-target="#branch-{{ branch.id }}">
                        <i class="far fa-trash-alt btn-outline-danger" title="delete"></i>
                    </a>
                    <!-- Modal -->
                    <div class="modal fade" id="branch-{{ branch.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="exampleModalLabel">Organization Delete</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are You Sure?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a href="{% url 'tickets:branch_delete' branch.id %}">
                                        <button type="button" class="btn btn-danger">Delete</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

tickets/templates/tickets/list.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} Tickets|{{ block.super }} {% endblock head_title %}
{% block content %}

    <div style="float:right">
        <a href='{% url "tickets:create" %}' class="btn btn-primary" style="margin-top:8px;">Add Record</a>
    </div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page"> Records</li>
        </ol>
    </nav>
    <hr>
    <div class="container">
        <form method="get">
            <div class="form-group row">
                <div class="col-md-3">
                    {{ filter.form.username }}
                </div>
                <div class="col-md-3">
                    {{ filter.form.date }}
                </div>

                <div class="col-md-5">
                    {{ filter.form.problem_domain }}
                </div>

            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    {{ filter.form.branch }}
                </div>
                <div class="col-md-3">
                    {{ filter.form.source }}
                </div>
                <div class="col-md-3">
                    {{ filter.form.status }}
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-success form-control">Filter</button>
                </div>
            </div>
        </form>
    </div>
    {#    <form method="GET" action="" class="offset-md-0">#}
    {#        <div class="form-group row">#}
    {#            <div class="col-md-3">#}
    {#                <select name="source" class="form-control">#}
    {#                    <option value="">Select Source</option>#}
    {#                    <option value="Call_in" {% if source_filter == "Call_in" %} selected="selected" {% endif %}>Call#}
    {#                        In#}
    {#                    </option>#}
    {#                    <option value="Call_out" {% if source_filter == "Call_out" %} selected="selected" {% endif %}>Call#}
    {#                        Out#}
    {#                    </option>#}
    {#                    <option value="CUG" {% if source_filter == "CUG" %} selected="selected" {% endif %}>CUG</option>#}
    {#                    <option value="Viber" {% if source_filter == "Viber" %} selected="selected" {% endif %}>Viber#}
    {#                    </option>#}
    {#                    <option value="Skype" {% if source_filter == "Skype" %} selected="selected" {% endif %}>Skype#}
    {#                    </option>#}
    {#                    <option value="Message" {% if source_filter == "Message" %} selected="selected" {% endif %}>#}
    {#                        Message#}
    {#                    </option>#}
    {#                </select>#}
    {#            </div>#}
    {#            <div class="col-md-3">#}
    {#                <select name="status" class="form-control">#}
    {#                    <option value="">Select Status</option>#}
    {#                    <option value="Open" {% if status_filter == "Open" %} selected="selected" {% endif %}>Open</option>#}
    {#                    <option value="Close" {% if status_filter == "Close" %} selected="selected" {% endif %}>Close#}
    {#                    </option>#}
    {#                    <option value="Pending" {% if status_filter == "Pending" %} selected="selected" {% endif %}>#}
    {#                        Pending#}
    {#                    </option>#}
    {#                </select>#}
    {#            </div>#}
    {##}
    {#            <button type="submit" value="filter" class="btn btn-success">Filter</button>#}
    {#        </div>#}
    {#    </form>#}


    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable ">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ message.tags }} !!</strong> {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <br>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>S.N.</th>
            <th>Username</th>
            <th>Contact</th>
            <th>Branch</th>
            <th>Problem Domain</th>
            <th>Status</th>
            <th>Remarks</th>
            <th>Issue Date</th>
            <th>Ticket</th>
            <th>Source</th>
            <th>Employee</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in filter.qs %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ obj.client_id }} </td>
                <td>{{ obj.contact }} </td>
                <td>{{ obj.branch_id }}</td>
                <td>{{ obj.problem_domain_id }} </td>
                <td>{{ obj.status }}</td>
                <td>{{ obj.remarks }}</td>
                <td>{{ obj.issue_date }}</td>
                <td>
                    {% if obj.ticket is not Null %}
                        {{ obj.ticket }}
                    {% endif %}
                </td>
                <td>{{ obj.source }}</td>
                <td>{{ obj.employee_id }}</td>
                <td>
                    <a href="{% url 'tickets:edit' obj.id %}">
                        <i class="fas fa-pen-square" title="edit"></i>
                    </a>
                    &nbsp;
                    {% if user.is_admin %}
                    <a href="{% url 'tickets:delete' obj.id %}" data-toggle="modal" data-target="#obj-{{ obj.id }}">
                        <i class="far fa-trash-alt btn-outline-danger" title="delete"></i>
                    </a>
                    {% endif %}

                    <!-- Modal -->
                    <div class="modal fade" id="obj-{{ obj.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="exampleModalLabel">Organization Delete</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are You Sure?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a href="{% url 'tickets:delete' obj.id %}">
                                        <button type="button" class="btn btn-danger">Delete</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

tickets/templates/tickets/problem_list.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} Tickets|{{ block.super }} {% endblock head_title %}
{% block content %}

    {% if user.is_admin %}
        <div style="float:right">
            <a href='{% url "tickets:problem_create" %}' class="btn btn-primary" style="margin-top:8px;">Add Problem</a>
        </div>
    {% endif %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item text-muted" aria-current="page"> Problem Domain</li>
        </ol>
    </nav>
    <hr>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable ">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ message.tags }} !!</strong> {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <table class="table table-bordered table-hover col-md-6 offset-3">
        <thead>
        <tr>
            <th>S.N.</th>
            <th>Name</th>
            {% if user.is_admin %}
                <th>Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for problem in problem_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td> {{ problem }}</td>
                {% if user.is_admin %}
                    <td>
                        <a href="{% url 'tickets:problem_edit' problem.id %}">
                            <i class="fas fa-pen-square" title="edit"></i>
                        </a> &nbsp;
                        <a href="{% url 'tickets:problem_delete' problem.id %}" data-toggle="modal"
                           data-target="#problem-{{ problem.id }}">
                            <i class="far fa-trash-alt btn-outline-danger" title="delete"></i>
                        </a>
                        <!-- Modal -->
                        <div class="modal fade" id="problem-{{ problem.id }}" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="exampleModalLabel">Organization Delete</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Are You Sure?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                        </button>
                                        <a href="{% url 'tickets:problem_delete' problem.id %}">
                                            <button type="button" class="btn btn-danger">Delete</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

tickets/templates/tickets/ticket_for_emp.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} Tickets|{{ block.super }} {% endblock head_title %}
{% block content %}

<div style="float:right">
    <a href='{% url "tickets:create" %}' class="btn btn-primary" style="margin-top:8px;">Add Ticket</a>
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Tickets List</a></li>
    </ol>
</nav>
<hr>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>S.N.</th>
        <th>Organization Name</th>
        <th>Contact</th>
        <th>Product</th>
        <th>Ticket Type</th>
        <th>Issue Date</th>
        <th>Completion Date</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
    {% if request.user.email == obj.employee_id.email %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'tickets:detail' obj.id %}">{{ obj.organization_id }}</a></td>
        <td> {{ obj.organization_id.mobile2 }}</td>
        <td> {{ obj.product_id }} </td>
        <td>{{ obj.ticket_type }}</td>
        <td>{{ obj.issue_date }}</td>
        <td>{{ obj.completion_date }}</td>
        <td>{{ obj.status }}</td>
        <td>
            <a href="{% url 'tickets:edit' obj.id %}">
                <i class="fas fa-pen-square" title="edit"></i>
            </a> &nbsp;
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>

{% endblock %}