mails/urls.py
from django.urls import path
from . import views

app_name = 'mails'

urlpatterns = [
    path('', views.email, name = 'list' ),
]

organizations/urls.py
from django.urls import path

from . import views

app_name = 'organizations'
urlpatterns = [
    path('', views.listview, name='list'),
    path('add/', views.createview, name='create'),
    path('<id>/edit/', views.editview, name='edit'),
    path('<id>/delete/', views.deleteview, name='delete'),
]

ticket_ms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('organizations/', include('organizations.urls')),
    path('tickets/', include('tickets.urls')),
    path('employees/', include('employees.urls')),
    path('products/', include('products.urls')),
    path('mails/', include('mails.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change_password/', views.user_password_change, name='change_password'),
    path('users/', views.user_listview, name='list'),
    path('users/<id>/edit/', views.user_editview, name='edit'),
    path('users/<id>/delete/', views.user_deleteview, name='delete'),
    path('users/add/', views.user_createview, name='create'),
]

organizations/models.py
from django.db import models

# Create your models here.
IS_ACTIVE = (
        ('YES', 'Yes'),
        ('NO', 'No'),
    )


class Organization(models.Model):
    class Meta:
        ordering = ['name']
    username = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=254)
    address = models.CharField(max_length=254, null=True, blank=True)
    phone = models.CharField(max_length=254, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    mobile = models.CharField(max_length=254, null=True, blank=True)
    is_active = models.CharField(max_length=254, choices=IS_ACTIVE, default=IS_ACTIVE[0][0])
    created_at = models.DateTimeField(auto_now_add=True) #Object created DateTime
    updated_at = models.DateTimeField(auto_now=True) #last modified DateTime

    def __str__(self):
        return self.username

organizations/forms.py
from django import forms

from .models import Organization


class CreateForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = [
            'username',
            'name',
            'address',
            'phone',
            'email',
            'mobile',
            'is_active',
        ]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'name'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'address'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'phone'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'abc@example.com'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'mobile number'}),
            'is_active': forms.Select(attrs={'class': 'form-control'}),
        }

organizations/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template

from users.decorators import admin_required
from .forms import CreateForm
from .models import Organization
from .utils import render_to_pdf
from ticket_ms.utils import render_pdf
# Create your views here.


@login_required
def listview(request):
    output = request.GET.get("output", "")

    queryset_list = Organization.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(name__icontains=query) |
            Q(address__icontains=query) |
            Q(username__icontains=query) |
            Q(mobile__icontains=query)
        ).distinct()

    paginator = Paginator(queryset_list, 10)

    page = request.GET.get('page')

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'object_list': queryset,
        'object_pdf_list': queryset_list,
    }

    if output == "pdf":
        return render_pdf('organizations/list_pdf.html', context, filename='clients.pdf')

    template_name = 'organizations/list.html'
    return render(request, template_name, context)


@login_required
@admin_required
def createview(request):
    form = CreateForm(request.POST, request.FILES)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        from django.contrib import messages
        messages.success(request, "Client added.")
        return HttpResponseRedirect("/organizations/")
    if form.errors:
        errors = form.errors

    template_name = 'organizations/forms.html'
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)


@login_required
def editview(request, id=None):
    instance = get_object_or_404(Organization, id=id)
    form = CreateForm(request.POST or None, request.FILES or None, instance=instance)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Client edited.")
        return HttpResponseRedirect("/organizations/")
    if form.errors:
        errors = form.errors

    template_name = 'organizations/form.html'
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)


@login_required
@admin_required
def deleteview(request, id=None):
    instance = get_object_or_404(Organization, id=id)
    instance.delete()
    messages.info(request, "Client deleted.")
    return redirect('organizations:list')


@login_required
def pdf_generate_view(request, *args, **kwargs):
    queryset = Organization.objects.all()
    template = get_template('organizations/org_list_pdf.html')
    context = {
        'object_list': queryset,
        'base_url': 'http://localhost:8000'
    }
    html = template.render(context)
    pdf = render_to_pdf('organizations/org_list_pdf.html', context)
    # return HttpResponse(pdf, content_type='application/pdf')
    return pdf

organizations/templates/organizations/form.html
{% extends "base.html" %}
{% block head_title %} {{ title }} | {{ block.super }} {% endblock head_title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'organizations:list' %}">Client List</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Client Detail</li>
    </ol>
</nav>
<hr>

<form method="POST" enctype="multipart/form-data" class="offset-md-3"> {% csrf_token %}
    <div class="form-group row">
        <label class="col-md-2 col-form-label">{{ form.username.label }} <span class="required-field">*</span></label>
        <div class="col-md-6">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label">{{ form.name.label }} <span class="required-field">*</span></label>
        <div class="col-md-6">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.address.label }} </label>
        <div class="col-sm-6">
            {{ form.address}}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.phone.label }}</label>
        <div class="col-sm-6">
            {{ form.phone }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.email.label }}</label>
        <div class="col-sm-6">
            {{ form.email}}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.mobile.label }}</label>
        <div class="col-sm-6">
            {{ form.mobile }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.is_active.label }}</label>
        <div class="col-sm-6">
            {{ form.is_active }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary offset-md-2">Update</button>

</form>

{% endblock %}

organizations/templates/organizations/forms.html
{% extends "base.html" %}
{% block head_title %} {{ title }} | {{ block.super }} {% endblock head_title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'organizations:list' %}">Client List</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Client</li>
    </ol>
</nav>
<hr>

<form method="POST" enctype="multipart/form-data" class="offset-md-3"> {% csrf_token %}
    <div class="form-group row">
        <label class="col-md-2 col-form-label">{{ form.username.label }} <span class="required-field">*</span></label>
        <div class="col-md-6">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label">{{ form.name.label }} <span class="required-field">*</span></label>
        <div class="col-md-6">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.address.label }}</label>
        <div class="col-sm-6">
            {{ form.address}}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.phone.label }}</label>
        <div class="col-sm-6">
            {{ form.phone }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.email.label }}</label>
        <div class="col-sm-6">
            {{ form.email}}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.mobile.label }}</label>
        <div class="col-sm-6">
            {{ form.mobile }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.is_active.label }}</label>
        <div class="col-sm-6">
            {{ form.is_active }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary offset-md-2">Add Client</button>
</form>

{% endblock %}

organizations/templates/organizations/list.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} Organizations|{{ block.super }} {% endblock head_title %}
{% block content %}

    <div style="float:right">
        <a href='{% url "organizations:list" %}?&output=pdf' class="btn btn-primary" style="margin-top:8px;"
           target="_blank">PDF
            Report</a> &nbsp;
        {% if user.is_admin %}
            <a href='{% url "organizations:create" %}' class="btn btn-primary active" style="margin-top:8px;">Add
                Client</a>
        {% endif %}
    </div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
            <li class="breadcrumb-item text-muted" aria-current="page"> Client
                List
            </li>
        </ol>
    </nav>
    <hr>

    <form method="GET" action="">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <input type="text" class="form-control" name="q" placeholder="Search Client"
                       value="{{ request.GET.q }}">
            </div>
            <div class="col-md-1">
                <input type="submit" value="Search" class="btn btn-success">
            </div>
        </div>
    </form>
    <br>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ message.tags }} !!</strong> {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>S.N.</th>
            <th>Username</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>E-mail</th>
            <th>Mobile</th>
            <th>Is active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ obj }}</td>
                <td>{{ obj.name }} </td>
                <td>
                    {% if obj.address is not Null %}
                        {{ obj.address }}
                    {% endif %}
                </td>
                <td>
                    {% if obj.phone is not Null %}
                        {{ obj.phone }}
                    {% endif %}
                </td>
                <td>
                    {% if obj.email is not Null %}
                        {{ obj.email }}
                    {% endif %}
                </td>
                <td>
                    {% if obj.mobile is not Null %}
                        {{ obj.mobile }}
                    {% endif %}
                </td>
                <td>{{ obj.is_active }}</td>
                <td>
                    <a href="{% url 'organizations:edit' obj.id %}">
                        <i class="fas fa-pen-square" title="edit"></i>
                    </a> &nbsp;
                    {% if user.is_admin %}
                        <a href="{% url 'organizations:delete' obj.id %}" data-toggle="modal"
                           data-target="#obj-{{ obj.id }}">
                            <i class="far fa-trash-alt btn-outline-danger" title="delete"></i>
                        </a>
                    {% endif %}
                    <!-- Modal -->
                    <div class="modal fade" id="obj-{{ obj.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="exampleModalLabel">Client Delete</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are You Sure?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a href="{% url 'organizations:delete' obj.id %}">
                                        <button type="button" class="btn btn-danger">Delete</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination ">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ object_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">next</a>
            <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>

{% endblock %}

organizations/templates/organizations/list_pdf.html
{% extends "pdf_base.html" %}

{% block content %}

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>S.N.</th>
        <th>Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>IT officer</th>
        <th>Mobile</th>
        <th>Is active</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in object_pdf_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td> {{ obj }} </td>
        <td>{{ obj.address }}</td>
        <td>{{ obj.phone }}</td>
        <td>{{ obj.contact_person2 }}</td>
        <td>{{ obj.mobile2 }}</td>
        <td>{{ obj.is_active }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

organizations/templates/organizations/org_list_pdf.html
{% load static %}
<html>
<head>
    <base href="{{ base_url }}"/>
    <title>Organizations Report</title>
    <link rel="stylesheet" href="{% static 'css/pdf.css' %}"/>
    <style type="text/css">
    </style>
</head>
<body>
<div>
    <h1 class="text-center">Organizations</h1>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>SN</th>
        <th>Date</th>
        <th>Type</th>
        <th>Category</th>
        <th>Description</th>
        <th>Amount</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td> {{ obj }} </td>
        <td>{{ obj.address }}</td>
        <td>{{ obj.phone }}</td>
        <td>{{ obj.contact_person2 }}</td>
        <td>{{ obj.mobile2 }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<hr>
</body>
</html>