employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.listview, name='list' ),
    path('add/', views.createview, name='create'),
    path('<id>/edit', views.editview, name='edit'),
    path('<id>/delete', views.deleteview, name='delete'),
    path('<id>/detail', views.detailview, name='detail'),
]

mails/urls.py
from django.urls import path
from . import views

app_name = 'mails'

urlpatterns = [
    path('', views.email, name = 'list' ),
]

organizations/urls.py
from django.urls import path

from . import views

app_name = 'organizations'
urlpatterns = [
    path('', views.listview, name='list'),
    path('add/', views.createview, name='create'),
    path('<id>/edit/', views.editview, name='edit'),
    path('<id>/delete/', views.deleteview, name='delete'),
]

ticket_ms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('organizations/', include('organizations.urls')),
    path('tickets/', include('tickets.urls')),
    path('employees/', include('employees.urls')),
    path('products/', include('products.urls')),
    path('mails/', include('mails.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'

urlpatterns = [
    path('', views.listview, name='list'),
    path('add/', views.createview, name='create'),
    path('<id>/edit/', views.editview, name='edit'),
    path('<id>/delete/', views.deleteview, name='delete'),
    path('branch_list/', views.branch_listview, name='branch_list'),
    path('branch_add/', views.branch_create_view, name='branch_create'),
    path('branch_list/<id>/branch_edit/', views.branch_edit_view, name='branch_edit'),
    path('branch_list/<id>/branch_delete/', views.branch_delete_view, name='branch_delete'),
    path('problem_list/', views.problem_listview, name='problem_list'),
    path('problem_add/', views.problem_create_view, name='problem_create'),
    path('problem_list/<id>/branch_edit/', views.problem_edit_view, name='problem_edit'),
    path('problem_list/<id>/branch_delete/', views.problem_delete_view, name='problem_delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change_password/', views.user_password_change, name='change_password'),
    path('users/', views.user_listview, name='list'),
    path('users/<id>/edit/', views.user_editview, name='edit'),
    path('users/<id>/delete/', views.user_deleteview, name='delete'),
    path('users/add/', views.user_createview, name='create'),
]

templates/includes/footer.html
{% if user.is_authenticated %}
<div class="footer">
  <div class="container">
    <div class="col-md-12 text-center">
      <p>©2018 Zeftware Solutions</p>
    </div>
  </div>
</div>
{% endif %}

templates/includes/partial_admin_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href='{% url "users:index" %}'><i class="fas fa-home white"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href='{% url "organizations:list" %}'>CLIENTS</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "tickets:list" %}'>RECORD</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "employees:list" %}'>EMPLOYEE</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "tickets:branch_list" %}'>BRANCH</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "tickets:problem_list" %}'>PROBLEM_DOMAIN</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "users:list" %}'>USER</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href='#'>{{request.user.username}}</a>
            </li>
            <li class="dropdown">
                <a href="#" class="" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false"><i class="fa fa-user-circle fa-2x white"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'users:change_password' %}" class="dropdown-item">Change Password</a>
                    <a href="{% url 'users:logout' %}" class="dropdown-item">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/includes/partial_employee_menu.html
{% load static %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href='{% url "users:index" %}'><i class="fas fa-home white"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href='{% url "tickets:list" %}'>RECORD</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "employees:list" %}'>EMPLOYEE</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "tickets:branch_list" %}'>BRANCH</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href='{% url "tickets:problem_list" %}'>PROBLEM_DOMAIN</a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href='#'>{{request.user.username}}</a>
            </li>
            <li class="dropdown">
                <a href="#" class="" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false"><i class="fa fa-user-circle fa-2x white"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'users:change_password' %}" class="dropdown-item">Change Password</a>
                    <a href="{% url 'users:logout' %}" class="dropdown-item">Logout</a>
                </div>
            </li>
        </ul>

    </div>
</nav>
{% endif %}