mails/urls.py
from django.urls import path
from . import views

app_name = 'mails'

urlpatterns = [
    path('', views.email, name = 'list' ),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_listview, name='list'),
    path('add/', views.product_createview, name='create'),
    path('<id>/edit', views.product_editview, name='edit'),
    path('<id>/delete', views.product_deleteview, name='delete'),
]

ticket_ms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('organizations/', include('organizations.urls')),
    path('tickets/', include('tickets.urls')),
    path('employees/', include('employees.urls')),
    path('products/', include('products.urls')),
    path('mails/', include('mails.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change_password/', views.user_password_change, name='change_password'),
    path('users/', views.user_listview, name='list'),
    path('users/<id>/edit/', views.user_editview, name='edit'),
    path('users/<id>/delete/', views.user_deleteview, name='delete'),
    path('users/add/', views.user_createview, name='create'),
]

products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=254)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms

from .models import Product


class CreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'description'}),
        }

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from users.decorators import admin_required
from .models import Product
from .forms import CreateForm

# Create your views here.


@login_required
def product_listview(request):
    queryset = Product.objects.all()
    context = {
        'object_list' : queryset
    }
    return render(request, 'products/list.html', context)


@login_required
@admin_required
def product_createview(request):
    form = CreateForm(request.POST or None)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect('/products/')
    if form.errors:
        errors = form.errors

    template_name = 'products/forms.html'
    context = {
        'form': form,
        'errors': errors
    }
    return render(request, template_name, context)


@login_required
@admin_required
def product_editview(request, id=None):
    instance = get_object_or_404(Product, id=id)
    form = CreateForm(request.POST or None, instance=instance)
    errors = None
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect("/products/")
    if form.errors:
        errors = form.errors

    template_name = 'products/form.html'
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)


@login_required
@admin_required
def product_deleteview(request, id=None):
    instance = get_object_or_404(Product, id=id)
    instance.delete()
    return redirect('products:list')

products/templates/products/form.html
{% extends "base.html" %}
{% block head_title %} {{ title }} | {{ block.super }} {% endblock head_title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'products:list' %}">Prducts </a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Product</li>
    </ol>
</nav>
<hr>

<form method="POST" class="offset-md-3"> {% csrf_token %}
    <div class="form-group row">
        <label class="col-md-2 col-form-label">{{ form.name.label }} <span class="required-field">*</span></label>
        <div class="col-md-6">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.description.label }} </label>
        <div class="col-sm-6">
            {{ form.description}}
        </div>
    </div>
    <button type="submit" class="btn btn-primary offset-md-2">Update</button>
</form>

{% endblock %}

products/templates/products/forms.html
{% extends "base.html" %}
{% block head_title %} {{ title }} | {{ block.super }} {% endblock head_title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'products:list' %}">Prducts </a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Product</li>
    </ol>
</nav>
<hr>

<form method="POST" class="offset-md-3"> {% csrf_token %}
    <div class="form-group row">
        <label class="col-md-2 col-form-label">{{ form.name.label }} <span class="required-field">*</span></label>
        <div class="col-md-6">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.description.label }}</label>
        <div class="col-sm-6">
            {{ form.description}}
        </div>
    </div>
    <button type="submit" class="btn btn-primary offset-md-2">Add Product</button>
</form>

{% endblock %}

products/templates/products/list.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} Products|{{ block.super }} {% endblock head_title %}
{% block content %}

<div style="float:right">&nbsp;
    {% if user.is_admin %}
    <a href='{% url "products:create" %}' class="btn btn-primary" style="margin-top:8px;">Add Pdoduct</a>
    {% endif %}
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'users:index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Products</a></li>
    </ol>
</nav>
<hr>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>S.N.</th>
        <th>Name</th>
        <th>Description</th>
        {% if user.is_admin %}
        <th>Action</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td> {{ obj }} </td>
        <td>{{ obj.description }}</td>
        {% if user.is_admin %}
        <td>
            <a href="{% url 'products:edit' obj.id %}">
                <i class="fas fa-pen-square" title="edit"></i>
            </a> &nbsp;
            <a href="{% url 'products:delete' obj.id %}" data-toggle="modal" data-target="#obj-{{ obj.id }}">
                <i class="far fa-trash-alt" title="delete"></i>
            </a>
            <!-- Modal -->
            <div class="modal fade" id="obj-{{ obj.id }}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="exampleModalLabel">Organization Delete</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are You Sure?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <a href="{% url 'products:delete' obj.id %}">
                                <button type="button" class="btn btn-danger">Delete</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}